Sprint 5/main page
GameMiddleFrontend/TheBestGame pull request #3
Opened 2022-04-03 11:00 UTC by TheRealMagic

2022-04-03 11:04 UTC, TheRealMagic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Главная страница — это мини-лендинг с презентацией вашей игры. Сейчас можно с ней не разгоняться и сделать сразу вход или авторизацию.](https://trello.com/c/b82oGja2/1-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%8D%D1%82%D0%BE-%D0%BC%D0%B8%D0%BD%D0%B8-%D0%BB%D0%B5%D0%BD%D0%B4%D0%B8%D0%BD%D0%B3-%D1%81-%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B5%D0%B9-%D0%B2%D0%B0%D1%88%D0%B5%D0%B9-%D0%B8%D0%B3%D1%80%D1%8B-%D1%81%D0%B5%D0%B9%D1%87%D0%B0%D1%81-%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE-%D1%81-%D0%BD%D0%B5%D0%B9-%D0%BD%D0%B5-%D1%80%D0%B0%D0%B7%D0%B3%D0%BE%D0%BD%D1%8F%D1%82%D1%8C%D1%81%D1%8F-%D0%B8-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%81%D1%80%D0%B0%D0%B7%D1%83-%D0%B2%D1%85%D0%BE%D0%B4-%D0%B8%D0%BB%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86)

2022-04-04 07:06 UTC, NadeSi commented on .eslintrc
> +    "@typescript-eslint/ban-ts-comment": "off"
На мой взгляд, не стоит использовать это правило. Можем потом огрести там, где ошибки игнорируются

2022-04-04 07:06 UTC, NadeSi commented on src/styles/main-page.scss
> +$mainBackgroundColor: #497f4a;
Может сразу выносить переменные с цветом в отдельный файл? Так будет проще поддерживать единую стилистику приложения

2022-04-04 07:10 UTC, NadeSi commented on src/styles/main-page.scss
> +$mainBackgroundColor: #497f4a;
Нашла в другой ветке style-variables.scss)

2022-04-04 07:11 UTC, NadeSi approved these changes

2022-04-04 12:51 UTC, bercly0b commented on src/components/pages/main-page.tsx
> +// @ts-ignore
а давай просто вебпак и тайпскрипт научим нормально резолвить импорты svg? 
например [так](https://stackoverflow.com/a/45887328)

2022-04-04 12:52 UTC, bercly0b requested changes
и картинка достаточно большая, почти 70КБ. прогони ее пож через какой нибудь оптимизатор

2022-04-04 19:16 UTC, merged