Sprint 5/login page
GameMiddleFrontend/TheBestGame pull request #4
Opened 2022-04-03 21:37 UTC by TheRealMagic

2022-04-03 21:37 UTC, TheRealMagic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница входа.](https://trello.com/c/eNbbFZdh/2-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0)

2022-04-04 07:31 UTC, NadeSi requested changes

2022-04-04 07:31 UTC, NadeSi commented on src/validators/ValidatorFactory.ts
> +    if (field.includes('name')) {
Очень смущают зашитые имена переменных. Возможно стоит разделить модель (описание переменных, и их соответствие валидатору) и а тут возвращать валидатор в соответствии с моделью

2022-04-04 19:09 UTC, NadeSi approved these changes

2022-04-06 07:26 UTC, bercly0b commented on package.json
> +    "formik": "^2.2.9",
formik должен быть в dependencies

2022-04-06 07:26 UTC, bercly0b commented on package.json
> +    "yup": "^0.32.11"
и yup тоже в dependencies

2022-04-06 07:29 UTC, bercly0b commented on src/services/loginAPI.tsx
> +          resolve(response.text());
тут точно text надо? не json?

2022-04-06 07:33 UTC, bercly0b commented on src/services/loginAPI.tsx
> +      return new Promise((resolve, reject) => {
а зачем тут вложенный промис? 
можно же сделать 
```
if (response.status !== 200) {
    throw ...
}
```
и тогда мы в следующий catch провалимся

2022-04-06 07:37 UTC, bercly0b commented on src/components/pages/login-page/login-page.tsx
> +function onLoginFormSubmit(data: FormikValues) {
эта функция наверное должна быть внутри компонента?
мы же захотим в результате похода в апи что то записать в стейт компонента?

2022-04-06 07:38 UTC, bercly0b commented on src/components/pages/login-page/login-page.tsx
> +        initialValues={{
такое лучше не делать, потому что на каждый рендер будет создаваться новая ссылка на объект.
лучше вынести это наружу компонента в константу и тут ее использовать

2022-04-06 07:39 UTC, bercly0b commented on src/components/pages/login-page/login-page.tsx
> +        onSubmit={(values) => {
тут тоже, каждый раз новая ссылка на функцию. 
`onSubmit={onLoginFormSubmit}`
либо если коллбек переедет в компонент, то его нужно будет обернуть в [useCallback](https://ru.reactjs.org/docs/hooks-reference.html#usecallback)

2022-04-06 07:40 UTC, bercly0b commented on src/components/pages/login-page/types.tsx
> +    .max(20, 'От 3 до 20 символов')
а почему все проверки закоменчены?

2022-04-06 07:40 UTC, bercly0b requested changes
есть вопросы

2022-04-06 08:18 UTC, TheRealMagic commented on src/services/loginAPI.tsx
> +          resolve(response.text());
когда тестировал, при успезхе приходит ОК и все, а вот при свале json "{"reason": ""}", поэтому сделал так

2022-04-06 08:22 UTC, TheRealMagic commented on src/components/pages/login-page/types.tsx
> +    .max(20, 'От 3 до 20 символов')
пока для удобства тестирования)

2022-04-08 09:03 UTC, TheRealMagic commented on src/services/loginAPI.tsx
> +      return new Promise((resolve, reject) => {
хотел прокидывать текст ошибки и выводить условному пользователю, но он приходит в json

2022-04-08 09:46 UTC, merged