Sprint 5/auth api
GameMiddleFrontend/TheBestGame pull request #8
Opened 2022-04-08 15:43 UTC by TheRealMagic

2022-04-08 15:50 UTC, TheRealMagic commented
Пользователь глобально определяется, но пока без редакса никуда не передается

2022-04-08 15:52 UTC, TheRealMagic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Авторизация: регистрация и страница входа (уже с API, берите API из прошлого модуля).](https://trello.com/c/hf9NNQ6N/6-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0-%D1%83%D0%B6%D0%B5-%D1%81-api-%D0%B1%D0%B5%D1%80%D0%B8%D1%82%D0%B5-api-%D0%B8%D0%B7-%D0%BF%D1%80%D0%BE%D1%88%D0%BB%D0%BE%D0%B3%D0%BE-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8F)

2022-04-08 16:56 UTC, NadeSi requested changes

2022-04-08 16:56 UTC, NadeSi commented on src/components/pages/login-page/login-page.tsx
> +    LoginAPI.signIn(JSON.stringify(data))
Может все эти обработки оставить в сервисе? Чтобы в него передавать только data и получать уже обработанный результат

2022-04-08 16:56 UTC, NadeSi commented on src/components/pages/register-page/register-page.tsx
> +      <Popup open={!!popupMessage} onClose={() => setPopupMessage('')}>
Popup удобнее вынести в отдельный компонент, не раз еще к нему обращаться будем

2022-04-08 16:56 UTC, NadeSi commented on src/services/authAPI.tsx
> +const baseUrl = 'https://ya-praktikum.tech/api/v2';
дублируется в 3х файлах, может тоже вынести? Как вариант, создать общий класс, в котором есть основные заголовки, baseUrl

2022-04-10 14:41 UTC, TheRealMagic commented on src/components/pages/login-page/login-page.tsx
> +    LoginAPI.signIn(JSON.stringify(data))
немного не понял... в сервис отправляются значения полей из формы и возвращается результат - ок или ошибка

2022-04-10 21:40 UTC, NadeSi approved these changes

2022-04-10 21:40 UTC, NadeSi commented on src/services/signUpAPI.tsx
> +        credentials: 'include',
наверное можно тоже как заголовок по умолчанию добавить, если не пришло ничего другого

2022-04-11 15:15 UTC, bercly0b commented on src/components/common/avatar/avatar.component.tsx
> +  const handleInputChange = (event: ChangeEvent<HTMLInputElement>) => {
коллбеки бы в useCallback обернуть..

2022-04-11 15:17 UTC, bercly0b commented on src/components/pages/login-page/login-page.tsx
> +          .then(() => {
ой, а давай не будем вложенные промисы делать?)

2022-04-11 15:20 UTC, bercly0b commented on src/components/pages/settings/settings-page.tsx
> +  const FormPassword = () => {
а давайте придерижваться правила 1 файл на 1 компонент?
кажется так чище получается..

2022-04-11 15:22 UTC, bercly0b commented on src/services/APIUtils.tsx
> +  getFetch(config: fetchConfig, endOfURL?: string) {
почему не просто `fetch`?)
и `endOfURL` я бы назвал `path`
и обычно сначала урл, а потом параметры, если смотреть на тот же `fetch`)

2022-04-11 15:22 UTC, bercly0b commented on src/services/APIUtils.tsx
> +  getFetch(config: fetchConfig, endOfURL?: string) {
потому что параметров может не быть и без них можно сделать запрос, а без урла нет

2022-04-11 15:23 UTC, bercly0b commented on src/services/signUpAPI.tsx
> +        credentials: 'include',
ага, я тоже за то, что бы сделать в APIUtils набор дефолтных параметров и подставлять их внутри. а не передавать каждый раз снаружи

2022-04-11 15:24 UTC, bercly0b commented on src/services/signUpAPI.tsx
> +        credentials: 'include',
и еще у APIUtils можно сделать методы get, post, etc..
и тогда в большинстве случаев можно вообще обойтись без параметров и читаться такое будет легко

2022-04-11 15:24 UTC, bercly0b approved these changes

2022-04-11 19:02 UTC, merged